services:
  web:
    build: .
    container_name: dj_search_engine
    ports:
      - "8008:8008"
    depends_on:
      - qdrant
    env_file:
      - .env  
    environment:
      - QDRANT_URL=http://dj_qdrant:6333
    networks:
      - dj_network

  qdrant:
    container_name: dj_qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - db-data:/qdrant/storage
    networks:
      - dj_network

networks:
  dj_network:

volumes:
  db-data: